#+TITLE: (转)西工大计算机专业本科三年学习感悟[二]
#+OPTIONS: ^:{} num:nil html-style:nil H:2 html-postamble:nil
#+HTML_HEAD: <link href="/css/blog.css" rel="stylesheet" type="text/css">
#+CATEGORY: blog

前几日发了一贴《西工大计算机专业本科三年学习感悟 》，但是重点不知不觉放在了语言上，关于专业的学习谈及的甚少，我约了三个班上的同学让他们写点心得。

这里的两篇希望CS专业的同学能好好看看，最好保存一下。不能将其称作补充了，因为他们写的比我要深刻多了。另一位同学的文章比较长还没完成，过几天再发。我本来想给关键词加色的，但是却无从下手.
 
* 竹谈算法
    棋局的发展是从开局，中局到残局，但象棋专业队的训练却是从残局，开局到中局，并且开局和残局的发展从未停止，中局的搏杀最见功力。

    残局之于象棋好比算法之于软件；语言，面向对象等方法，设计模式，软件工程之流则为开局；你的工作重点应在中局。没有合格的开局，将使你未能施展功力便郁闷地被斩落马下；没有长期大量积累的过硬的残局知识，你便不知把复杂的中局引向何方。处在中局，你便是一个掮客，一面提炼俗物的数学本质，一面组合你所熟知的各种算法，最终促成以巴和谈。

    通常被提及的算法是指运筹学，排队论，组合数学，初等数论等描述的离散世界，但数值算法，计算几何等表现的却是另外半边天地。

    那些被循环变得强大的几行简单语句定会使你惊叹与陶醉。

    不仅仅是是针对算法的学习，学而不思则罔与思而不学则怠的权衡与交错是促使进步的名言警句。
 
* 杨德刚谈计算机专业学习
   计算机科学与技术，总是犹抱琵琶半遮面，让我很难看清它的方向，其实这不是学科本身的问题，而是我们的教育。

   我们的计算机教育最大的缺失不是我们课程设置的不全，也不是我们的教学方法太没新意，而是一些人所倡导的点到为止，或曰浅尝辄止。

   无论上什么课，只要一遇到比较深的、涉及到一些计算本质的东西，我们可爱的老师不是很快的掠过，就是叫我们知道有这个即可，真搞不清他们是怎么想的，这样培养的学生能做什么，照猫画虎？依葫芦画瓢？那这样我们只能永远的跟在人家的后面，永远摆脱不了模仿、模仿、再模仿的命运，我们在计算机界永远也只能是个矿工，不会是矿主，因为我们不会开矿。

   作为学计算机的学生，必须要追本溯源，程序设计语言如C、JAVA、C++、Python等等不计其数，其实只不过是基本的计算理论的不同描述而已，不会跳出图灵机的圈子，至于算法则只是对基本运算步骤的优化。硬件是实现逻辑的具体手段，软件则是我们问题求解的接口。而所有这些的理论基础那就是数学，数学是基础，作为计算机系的学生尤其如此，一定不能忽视数学，虽说我们感觉上好像数学跟计算机课程关系不大，但是只要你想真正的理解计算机、想不只做一个软件民工，那么数学就是你选择。

   当然，这里的数学是跟计算相关的数学，并不是说每个人都像数学系学生那样，面面俱到。主要是算法、数论、自动机理论、可计算性理论、组合数学、计算几何、拓扑学、离散数学、数学分析、计算数学、随机过程、概率论等，这些都是计算本质的东西，是眼花缭乱的计算机技术背后的东西，只要学好了这些，那么对于具体的计算机技术，那也就只是对号入座罢了。
 
* 介绍下两位作者
 竹一直迷茫于尘世，直到大三接触博弈论并以之解释世界才摆脱桎梏，大三之后一直想写一个Prolog解释器，目前还没实现，但我相信他会完成这个目标的。他花了大量时间练习ACM试题，但是并没有去参加任何比赛,原因未知。因为大三最后一学期计算机控制被神奇的挂掉，失去了保研资格，现准备考某知名高校。这对于他是件好事，对于工大却是十足的损失。

德刚学习踏实，功底扎实，大三学年平均学分积第一，目前正在1，3系的选择上徘徊.希望所有计算机学院的学生都能随着学习深入逐渐对专业有这种全面深刻本质的认识。我们专业很杂，很可能你十分喜欢某一方面的东西，于是就把那当做全部。又因为某些原因我们专业被认为与软件开发结合紧密，导致你只看到了表面，却看不到实质。
