#+TITLE: (转)西工大计算机专业本科三年学习感悟[三]
#+OPTIONS: ^:{} num:nil html-style:nil H:2 html-postamble:nil
#+HTML_HEAD: <link href="/css/blog.css" rel="stylesheet" type="text/css">
#+CATEGORY: blog

 老牛谈计算机学习体会
* 
 仅仅只是本人的一些经历和感悟，仅供参考。

  进入西工大计算机学院有点偶然因为我比较喜欢军事，但是在报志愿是突然对中国的军工体制产生了很强烈的质疑（让人心痛的航空发动机啊），我觉得西工大最强的专业就基本上是中国军工的短板并且受制于体制而很难改变，所以我报了一个大众的行业－－计算机，虽然我的成绩可以上三航之类的专业。

  到了西工大，我发现计算机学院的名声不太好也似乎不被学校重视。我有点对我的未来有点担心，我不知道该如何面对这个和我的想象不一样的计算机学院，而上的课程也加剧了我的担心－－一个和书本一样的PPT和一本浓缩的就像PPT的课本以及一张由前三年试卷组合而成的试卷（是的，是离散数学）。我用了一个月适应大学的生活，但是我用了三年时间去消除我对未来的担心，虽然不太成功但是我还是想说出来，因为我从中学到了很多并且这可能对你也有用如果你也担心你的未来的话。

  说句题外话，如果你是被调剂到计算机学院的话，请别伤心，很多人和你一样。虽然我的第一志愿是计算机（是的，你可能比我更了解西工大的计算机学院），但是我了解你的感受。但是我不会试着去安慰你，强者需要适应一个不太美好的环境并且去提升自己。让自己对“计算机”[fn:3]产生兴趣吧，如果你不能在第一学年考进前5%[fn:1]。当然我说的计算机可能不是你所认为的计算机，所以我加了引号。后面我会告诉你我眼中的计算机是什么，但是我要先谈谈我的大学三年是如何过的。

  经历过那个不太让人满意的第一学期，我对我的大学生活和计算机专业产生了很大的迷茫。为了让我不再迷茫或者至少减少一点迷茫，我开始大量的阅读计算机专业的书籍（绝大多数是国外教材的中译本）。

  在大一下学期我看了《计算机系统概论》这本书，从中对计算机有了一个初步的概貌性质的理解。那本书里对汇编的讲述让我喜欢上了计算机的底层的东西，而这也使得我可以在大三的汇编课上不用听老师讲解X86汇编，虽然吴晓老师讲得很好。金工实习时我开始看C＋＋，因为之前我也看了基本C语言的国外教材基本上适应了国外教材的风格，所以我学C＋＋时看了一些国外的教材，一开始的《面向对象程序设计(原书第2版):C++语言描述》，到以后的《C＋＋编程思想》第一卷，《C＋＋primer》。C＋＋我是用了不少时间的但是在以后的学习中却没有怎么使用（数据结构要用C，用C＋＋中的STL就没太大的效果了，算法STL中队列、栈就基本可以了）。但是通过学习C＋＋也锻炼了自己的毅力，了解了面向对象的一些概念，这比大二跟着老师学习Java强多了，更何况老师就没讲面向对象的东西，只讲了Java的语法。因为大一看了一本计算机组成原理的书《计算机系统结构：a networking approach》以及《编程卓越之道》第一卷，所以对计算机体系结构和计算机底层比较有兴趣，所以大二我主要看了一些这方面的书，比如《计算机组成：结构化方法，《深入理解计算机系统》等。在软件方面，我感觉我对C语言本身的理解已经有一定的程度了，就想看一下开源软件的源代码学习学习，所以就看了《代码阅读方法与实践》这本书，但是看完这本书我也没有掌握要领，或许只有经历过几个像样的软件项目后才可以吧。大三有很多重要的课，像计算机网络、操作系统、汇编、编译原理之类的，所以我跟着课程的安排看了一些“大部头”，感觉还很有收获，比课本强多了。找空闲看了看K＆R、《程序设计实践》，感触颇多，有温故知新也有茅塞顿开，总之经典制所以是经典，总是有让人感叹、让人钦佩的东西的。

以上是我大学三年的一些缩影吧，多少有些枯燥但是很有趣－－每一点的知识积累都要包含汗水但也让我充实，带着一点成就感:-) [fn:2]
* 
下面是我的一点想法。

计算机到底是什么，上层应用纷繁复杂看不清是潮流还是浪涌而底层却相对简洁稳定，我们学习着十几年甚至几十年就有的计算机组成和体系结构的基本原理，却几乎没有人使用九十年代末的Netscape的浏览器。计算机技术在发展，而支撑它的基本原理基本理念却历久弥新，就像cache（分层）、分时、流水、模块化等等。CPU的速度已今非昔比，可是解决问题的基本方法仍然是对具体问题的抽象、归类、分解。以前的程序员在CUI下使用PL/I、Fortran，现在的程序员在GUI下使用C系列的语言，除去语言的差别、语法的醣衣，程序员解决实际问题的方法却没有改变，改变的只是工具！考虑一下，除了C语言本身和专业课上学到的专有名词，你还学会了什么。你是否学会了以计算机的角度去看问题、思考问题？今天的你是否比以往的你在对计算机的理解和思考上有了进步？

“你所掌握的，也是我认为并希望的，就是智慧：那种看到这一机器比你第一次站在它面前是能做得更多的能力，这样你才能将它向前推进”
                                                                                                     Alan J. Perlis

计算机是一种思考、解决问题的方式！一种利用有限的资源去解决复杂问题的思想和实践，cache是，分时是、流水也是。所以，学习计算机不是学语言也不是ACM，而是思考它的体系结构、它的软硬件的底层实现以及它们所体现出的那种智慧，那种对有限资源的无限利用和在种种限制下的层出不穷的思想火花与神来之笔。

数学与计算是有区别的，就像真正的计算机教育和我们现在的计算机教育的区别一样大。思想与技能、艺术与技巧，前者是人的内在修养，后者是人的生存手段。让读书成为一种乐趣，不要为了面包而读书。
最后，送大家一句话：在一个以争创一流为口号的二流的学校里，要付出自己二倍的努力才能使自己不那么“二”，与君共勉之。


[fn:1] 老牛的意思是如果对“计算机”[n3]没兴趣，那么就努力考到前5%然后选择转专业，否则，只能踏实学习，逼自己产生兴趣了
[fn:2] 老牛这段本来写的很多，至少前天晚上他写的内容已不止现在的全篇这么少，其中也列了许多对计算机学习有价值的书目，但是最终发给我的这个版本却很短，也去掉了大量的书籍名称，我想可能是他希望突出文章的后半部分，这种很用心的删减也许对于许多同学并不是好事，但是我不可能要求他把删去的再加上，希望大家能用心看，如果大一就能模糊的树立起这种意识，那么对计算机的学习定会早日走向正途的。
[fn:3] 计算机这里老牛想指的什么，还需要慢慢领悟，可参考文章后半部分。

* 
 这次做的"征文"基本结束了，另外两个同学还都没给我回应，另外两个是我们这届大牛，所以估计是太忙了，大家也知道现在是特殊时期，大一很兴奋，大四很纠结。如果那两位牛人的文章能请到，还会有下一篇，不然这个系列到此就完结了。如果有对这个专业很感兴趣的同学，可以加QQ群:90405766，特别欢迎CS专业的同学。因为对于别的专业，我觉得大家还是要把精力花在本专业的学习上，不要被某些花哨的所谓计算机技术迷惑了，耽误了时间，当然，如果特别有爱，也是一样欢迎~
另外两篇重新列举在这，如果没看过的同学可以看看，我真的觉得结果比我期望的好很多，很多同学能积极讨论，发表意见，提出批评。而且征来的文章都比我自己写的更有价值(尽管对于非CS的同学价值不是很大，但是在一定程度为这个专业正本清源，对于由于各种原因新进入这一领域同学也是很有帮助)，我没想到他们的理解和表述都那么深刻，虽然天天和他们一起生活，聊天探讨，但从这三篇短文中我也学到了很多，感觉把我们平时含糊的讨论到的某些东西理清晰的表述出来了。
